config/routes.rb
Rails.application.routes.draw do

  namespace :auth do
    get 'login'
    get 'register'
    get 'sign_out'
    post 'sign_in'
    post 'sign_up'
  end

  resources :collections, shallow: true do
    resources :monuments, shallow: true do
      resources :pictures
    end
  end

  resources :categories

  root to: 'collections#index'

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :monuments
  belongs_to :user

end

app/models/collection.rb
class Collection < ActiveRecord::Base

  belongs_to :user
  has_many :monuments, dependent: :delete_all

end

app/models/monument.rb
class Monument < ActiveRecord::Base

  has_many :pictures, dependent: :delete_all
  belongs_to :category
  belongs_to :collection

end

app/models/picture.rb
class Picture < ActiveRecord::Base

  belongs_to :monument
  mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  has_many :collections
  has_many :categories

  attr_accessor :password_digest

  validates :login, presence: true, length: { minimum: 6 }
  validates :password, presence: true, length: { minimum: 6 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :check_login
  helper_method :current_user

  def check_login
    if current_user.nil?
      render 'auth/login'
    end
  end

  private

  def current_user
    User.find(session[:id])
  end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController

  skip_filter :check_login

  def sign_in
    login = params[:login]
    password = params[:password]
    user = User.find_by_login(login).try(:authenticate, password)
    validate(user, 'Incorrect username and/or password')
  end

  def sign_up
    login = params[:login]
    password = params[:password]
    user = User.create(login: login, password: password)
    validate(user, 'Could not register user')
  end

  def sign_out
    session.delete(:id)
    redirect_to root_path
  end

  private

  def validate user, error_msg
    if user
      session[:id] = user.id
    else
      flash[:error] = error_msg
    end
    redirect_to root_path
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = current_user.categories
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_url, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      redirect_to categories_url, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name).merge(user: current_user)
    end

end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController

  before_action :set_collection, only: [:show, :edit, :update, :destroy]

  def index
    @collections = current_user.collections
  end

  def new
    @collection = Collection.new
  end

  def create
    @collection = Collection.new(collection_params)

    if @collection.save
      redirect_to collections_url, notice: 'Collection was successfully created.'
    else
      render :new
    end
  end

  def update
    if @collection.update(collection_params)
      redirect_to collections_url, notice: 'Collection was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @collection.destroy
    redirect_to collections_url, notice: 'Collection was successfully destroyed.'
  end

  private
    def set_collection
      @collection = Collection.find(params[:id])
    end

    def collection_params
      params.require(:collection).permit(:name).merge(user: current_user)
    end
end

app/controllers/monuments_controller.rb
class MonumentsController < ApplicationController

  before_action :set_collection_and_monument, only: [:show, :edit, :update, :destroy]
  before_action :set_categories, only: [:new, :edit]

  def index
    @collection = Collection.find(params[:collection_id])
    @monuments = @collection.monuments
  end

  def edit
    @path = monument_path(@monument)
  end

  def new
    @monument = Monument.new
    @collection = Collection.find(params[:collection_id])
    @path = collection_monuments_path(@collection, @monument)
  end

  def create
    @collection = Collection.find(params[:collection_id])
    @monument = Monument.new(monument_params)
    @monument.collection = @collection

    if @monument.save
      redirect_to collections_url, notice: 'Monument was successfully created.'
    else
      render :new
    end
  end

  def update
    if @monument.update(monument_params)
      redirect_to collections_url, notice: 'Monument was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @monument.destroy
    redirect_to collections_url, notice: 'Monument was successfully destroyed.'
  end

  private
    def set_collection_and_monument
      @monument = Monument.find(params[:id])
      @collection = @monument.collection
    end

    def set_categories
      @categories = current_user.categories.map {|cat| [cat.name, cat.id] }
      @categories = [['---', '']] + @categories
    end

    def monument_params
      params.require(:monument).permit(:name, :description, :category_id)
    end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  before_action :set_monument_and_picture, only: [:show, :edit, :update, :destroy]

  def edit
    @path = picture_path(@picture)
  end

  def new
    @picture = Picture.new
    @monument = Monument.find(params[:monument_id])
    @path = monument_pictures_path(@monument, @picture)
  end

  def create
    @monument = Monument.find(params[:monument_id])
    @picture = Picture.new(picture_params)
    @picture.monument = @monument

    if @picture.save
      redirect_to collections_url, notice: 'Picture was successfully created.'
    else
      render :new
    end
  end

  def update
    if @picture.update(picture_params)
      redirect_to collections_url, notice: 'Picture was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @picture.destroy
    redirect_to collections_url, notice: 'Picture was successfully destroyed.'
  end

  private
    def set_monument_and_picture
      @picture = Picture.find(params[:id])
      @monument = @picture.monument
    end

    def picture_params
      params.require(:picture).permit(:name, :description, :image)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label 'Category:' %>
  <%= f.text_field :name %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<table>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.name, category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %> <%= link_to 'Back', collections_url %>

app/views/categories/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/collections/_form.html.erb
<%= form_for(@collection) do |f| %>
  <% if @collection.errors.any? %>
    <div id="error_explanation">

      <ul>
      <% @collection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label 'Collection:' %><br>
  <%= f.text_field :name %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<%= render 'form' %>

<%= link_to 'Back', collections_path %>

app/views/collections/index.html.erb
<% @collections.each do |collection| %>
  <h1>Collection: <%= collection.name %></h1>
    <%= link_to 'Edit', edit_collection_path(collection) %>
    <%= link_to 'Destroy', collection, method: :delete, data: { confirm: 'Are you sure?' } %>
  <div class='monuments'>

    <% collection.monuments.each do |monument| %>
      <h2>Monument: <span class='monument-name'><%= monument.name %></span></h2>
      <%= link_to 'Edit', edit_monument_path(monument) %>
      <%= link_to 'Destroy', monument, method: :delete, data: { confirm: 'Are you sure?' } %>
      <p>Category: <span class='category-name'><%= monument.category.try(:name) %></span> <%= link_to 'Edit Categories', categories_url %></p>
      <p>Description: <%= monument.description %></p>

      <div class='pictures'>
        <% monument.pictures.each do |picture| %>
          <div class='picture'>
            <h3><%= picture.name %></h3>
            <%= link_to 'Edit', edit_picture_path(picture) %>
            <%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %>
            <p>Date: <%= picture.created_at %></p>
            <p>Description: <%= picture.description %></p>
            <img src='<%= picture.image %>' style='width: 100px'>
          </div>
        <% end %>
        <br>
        <%= link_to 'Add Picture', new_monument_picture_path(monument) %>
      </div>

    <% end %>
    <br>
    <%= link_to 'Add Monument', new_collection_monument_path(collection) %>
  </div>
<% end %>

<br>

<%= link_to 'Add Collection', new_collection_path %>

app/views/collections/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', collections_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HitFox Case Study</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: name %>
  <% end -%>

  <% if current_user.present? %>
    <%= link_to 'Sign out', auth_sign_out_path %> <br>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/monuments/_form.html.erb
<%= form_for(@monument, url: @path) do |f| %>
  <% if @monument.errors.any? %>
    <div id="error_explanation">

      <ul>
      <% @monument.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label 'Monument:' %>
  <%= f.text_field :name %>
  <br>
  <%= f.label 'Description:' %>
  <%= f.text_area :description %>
  <br>
  <%= f.label 'Category:' %>
  <%= f.select(:category_id, @categories) %>

  <% if @categories.any? %>
    <%= link_to 'Edit Categories', categories_url %>
  <% else %>
    <%= link_to 'Add Category', new_category_url %>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/monuments/edit.html.erb
<%= render 'form' %>

<%= link_to 'Back', collections_path %>

app/views/monuments/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', collections_path %>

app/views/pictures/_form.html.erb
<%= form_for(@picture, url: @path) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">

      <ul>
      <% @picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label 'Picture name:' %>
  <%= f.text_field :name %>
  <br>
  <%= f.label 'Description:' %>
  <%= f.text_area :description %>
  <br>
  <%= f.label 'Image:' %>
  <%= f.file_field :image %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<%= render 'form' %>

<%= link_to 'Back', collections_url %>

app/views/pictures/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', collections_url %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<%= @picture.name %>
<%= @picture.description %>
<td><img src='<%= @picture.image.url %>' /></td>

<br>

<%= link_to 'Edit Picture', edit_picture_path(@picture) %> |
<%= link_to 'Back to Monument', monument_path(@monument) %>